#!/usr/bin/env perl
#
# name     : find-package, find package in debian
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 Oct 31
# modified : 2012 Nov 25
#

use strict;
use warnings;
use feature qw(say);
use LWP::Simple;
use HTML::TableExtract;

sub find_package {
  my ($file) = @_;

  $file = qx(readlink -f $file) if -l $file;
  chomp $file;

  my $url  = "http://packages.debian.org/file:$file";
  my $page = get($url);

  my $te = HTML::TableExtract->new( headers => [qw(File Packages)] );
  $te->parse($page);

  for my $row ( $te->rows ) {
    my $file = $row->[0];
    next if $file =~ /File/;

    my $package = $row->[1];
    next if $package =~ /Packages/;

    $package =~ s/\A\s+(.*)\s+\z/$1/m;
    say "* $file from $package";
  }
}

my $file = shift;
die "Usage: $0 </path/to/file>\n" unless $file;
find_package($file);
