#!/usr/bin/env python
#
# name     : find-ip, find vip or rip
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2014 Jul 18
# modified : 2014 Jul 18
#

import json
import sys
import requests


def find_ip(ip, ip_type='rip'):
    api_url = 'http://duomo.intra.sina.com.cn/?r=duomoRest/api'
    post_data = {'action': 'getByMember', 'rip': ip + ':80'}
    if ip_type == 'vip':
        post_data = {'action': 'getByVip', 'vip': ip + ':80'}
    r = requests.post(api_url, data=json.dumps(post_data))
    status_code = r.status_code
    if status_code == 200:
        get_data = r.json()
        status = get_data['status']
        if status == 0:
            return get_data['datas']
        else:
            print(status)
    else:
        print(status_code)


def parse_data(data, ip_type='rip'):
    ips = []
    for item in data:
        ip_list = item['virtualaddress']
        if ip_type == 'vip':
            ip_list = item['poolmember']
        for element in ip_list:
            ip = element['ip']
            port = element['port']
            ip_port = ip + ':' + port
            ips.append(ip_port)
    ips = set(ips)
    ips = list(ips)
    ips.sort()
    for ip in ips:
        print(ip)


if __name__ == '__main__':
    args = len(sys.argv) - 1
    if args == 1:
        ip = sys.argv[1]
        data = find_ip(ip)
        parse_data(data)
    elif args == 2:
        ip_type = sys.argv[1]
        ip = sys.argv[2]
        data = find_ip(ip, ip_type)
        parse_data(data, ip_type)
    else:
        print('Usage: find-ip <ip> or find-ip [<vip|rip>] <ip>')
        sys.exit(1)
