#!/usr/bin/env python
#
# name     : find-vip, find vip
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2014 Jul 18
# modified : 2014 Jul 18
#

import json
import sys
import requests


def find_vip(ip):
    api_url = 'http://duomo.intra.sina.com.cn/?r=duomoRest/api'
    post_data = {'action': 'getByMember', 'rip': ip}
    r = requests.post(api_url, data=json.dumps(post_data))
    status_code = r.status_code
    if status_code == 200:
        get_data = r.json()
        status = get_data['status']
        if status == 0:
            return get_data['datas']
        else:
            print(status)
    else:
        print(status_code)


def parse_data(data):
    ips = []
    for item in data:
        vip = item['virtualaddress']
        for element in vip:
            ip = element['ip']
            port = element['port']
            ip_port = ip + ':' + port
            ips.append(ip_port)
    ips = set(ips)
    ips = list(ips)
    ips.sort()
    for ip in ips:
        print(ip)


if __name__ == '__main__':
    try:
        ip = sys.argv[1]
    except:
        print('Usage: find-vip <ip>')
        sys.exit(1)
    data = find_vip(ip)
    parse_data(data)
