#!/usr/bin/env python
#
# name     : find-ip, find vip or rip
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2014 Jul 18
# modified : 2014 Jul 21
#

import json
import sys

try:
    import requests
except:
    print('Please run `pip install requests`')
    sys.exit(2)


def find_ip(ip, ip_type='rip'):
    api_url = 'http://duomo.intra.sina.com.cn/?r=duomoRest/api'
    sep = ':'
    if sep not in ip:
        ip = ip + ':80'
    post_data = {'action': 'getByMember', 'rip': ip}
    if ip_type == 'vip':
        post_data = {'action': 'getByVip', 'vip': ip}
    r = requests.post(api_url, data=json.dumps(post_data))
    status_code = r.status_code
    if status_code == 200:
        get_data = r.json()
        status = get_data['status']
        if status == 0:
            return get_data['datas']
        else:
            print(status)
    else:
        print(status_code)


def get_ip(data, ip_type='rip'):
    ips = []
    for item in data:
        ip_list = item['virtualaddress']
        if ip_type == 'vip':
            ip_list = item['poolmember']
        for element in ip_list:
            ip = element['ip']
            port = element['port']
            ip_port = ip + ':' + port
            ips.append(ip_port)
    put_list(ips)


def get_pool(data):
    pools = []
    for item in data:
        pool_name = item['poolname']
        pools.append(pool_name)
    put_list(pools)


def put_list(item_list):
    item_list = set(item_list)
    item_list = list(item_list)
    item_list.sort()
    for item in item_list:
        print(item)


if __name__ == '__main__':
    args = len(sys.argv) - 1
    if args == 1:
        ip = sys.argv[1]
        data = find_ip(ip)
        get_ip(data)
        get_pool(data)
    elif args == 2:
        ip_type = sys.argv[1]
        ip = sys.argv[2]
        data = find_ip(ip, ip_type)
        get_ip(data, ip_type)
        get_pool(data)
    else:
        print('Usage: find-ip <ip[:port]> or find-ip [<vip|rip>] <ip[:port]>')
        sys.exit(1)
