#!/bin/sh
#
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# modified : 2012 Jun 24
#

repo=$1

if [ -z "$repo" ]
then
  echo "Usage: github-init <repo>"
  exit 1
fi

if [ ! -d "$repo" ]
then
  mkdir "$repo"
fi

cd "$repo"

git init
git remote add origin git@github.com:xuxiaodong/"$repo".git

exit 0
