#!/usr/bin/env ruby
#
# name     : gmail, gmail information for mobar
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 Jul 30
# modified : 2012 Jul 31
#

require 'inifile'
require 'gmail_xoauth'

gmail = IniFile.new("#{Dir.home}/.secret")['gmail']
gmail_token = gmail['token']
gmail_token_secret = gmail['token_secret']

imap = Net::IMAP.new('imap.gmail.com', 993, usessl = true, certs = nil, verify = false)
imap.authenticate('XOAUTH', 'xxdlhy@gmail.com',
  :consumer_key => 'anonymous',
  :consumer_secret => 'anonymous',
  :token => gmail_token,
  :token_secret => gmail_token_secret,
)
msg_count = imap.status('INBOX', ['UNSEEN'])['UNSEEN']

puts "#{msg_count}m"
