#!/bin/bash
#
# name     : monbar, status bar for monsterwm
# modified : 2012 Aug 14
#

ff="/tmp/monsterwm.fifo"
[[ -p $ff ]] || mkfifo -m 600 "$ff"

# desktop names
ds=("dev" "www" "gfx" "etc")

# layout names
ms=("þ" "û" "ü" "ú" "ý")

while read -t 1 -r wmout || true; do
  if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
    read -ra desktops <<< "$wmout" && unset r
    for desktop in "${desktops[@]}"; do
      IFS=':' read -r d w m c u <<< "$desktop"
      ((c)) && fg="\\f7" i="${ms[$m]}" || fg="\\f1"
      ((u)) && w+='\f5!'
      r+="$fg${ds[$d]} ${w/#0/\\f6-} \\f1:: "
    done
    r="${r%::*}"
  fi
  printf "\\\l%s\\\r%s\n" "$r\\f4$i" "\\f7ê \\f4$(nowplaying) \\f7Ñ \\f4$(cpu) \\f7Æ \\f4$(mem) \\f7Ý \\f4$(net down) \\f7Ü \\f4$(net) \\f7Ì \\f4$(gmail) \\f7ð \\f4$(batter) \\f7í \\f4$(volume) \\f7· \\f4$(date +"%a, %b %d \\f7@ \\f4%R")"
done < "$ff" | bar &

# pass output to pipe and print to stdout
monsterwm > "$ff"
