#!/usr/bin/env perl
#
# name     : nowplaying, cmus status for conky
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 May 26
# modified : 2012 Nov 08
#

use strict;
use warnings;

my @cmus_status = qx(cmus-remote -Q 2>/dev/null);
my %metadata;

for my $line (@cmus_status) {
  $metadata{'status'} = $1 if $line =~ /^status (.*)$/;
  $metadata{'artist'} = $1 if $line =~ /^.*artist (.*)$/;
  $metadata{'title'}  = $1 if $line =~ /^.*title (.*)$/;

  unless ( defined $metadata{'artist'} or defined $metadata{'title'} ) {
    ( $metadata{'artist'}, $metadata{'title'} ) = ( $1, $2 )
      if $line =~ /^file.*?- (.*) -.*?- (.*)\./;
  }
}

if ( defined $metadata{'status'} ) {
  if ( $metadata{'status'} eq 'playing' ) {
    print "$metadata{'title'} by $metadata{'artist'}";
  }
  else {
    print $metadata{'status'};
  }
}
else {
  print "n/a";
}
