#!/usr/bin/env perl
#
# name     : perl-modep, parse perl module dependencies and create cpanfile
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2014 Apr 14
# modified : 2014 Apr 14
#

use strict;
use warnings;
use feature qw(say);
use File::Slurp qw(append_file);
use Module::Extract::Use;

die "Usage: $0 <perl file>\n" if @ARGV != 1;

my $file = shift;
say "Parsing $file ...";

my $extor   = Module::Extract::Use->new;
my @modules = $extor->get_modules($file);

my $cpanfile = 'cpanfile';
unlink $cpanfile if -e $cpanfile;
for my $mod (@modules) {
    next if $mod =~ /^[a-z]/;
    say "* $mod";
    my $line = "requires '$mod';\n";
    append_file( $cpanfile, $line );
}
