#!/usr/bin/env ruby
#
# name     : rename-pdf, rename pdf ebook
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 Aug 05
# modified : 2012 Aug 07
#

require 'escape'
require 'term/ansicolor'

include Term::ANSIColor

def parse_title(pdf)
  title = ''
  pdf = Escape.shell_command(["#{pdf}"])
  metadata = %x(pdfinfo #{pdf} 2>/dev/null).split(/\n/)
  metadata.each { |elt| title = $1 if elt =~ /^Title:\s*(.*?)$/ }
  title
end

abort "Usage: #$0 <*.pdf>" if ARGV.empty?

rename_count = skip_count = 0
ARGV.each do |pdf|
  title = parse_title(pdf)
  if title.empty? || title =~ /^\d+\.pdf/ || title =~ /untitled/
    puts "* [#{red}SKIP#{clear}] `#{pdf}' is empty title, skipping ..."
    skip_count += 1
    next
  else
    title += ".pdf"
    puts "* [ #{green}OK#{clear} ] Renaming `#{pdf}' to `#{title}' ..."
    File.rename pdf, title
    rename_count += 1
  end
end
puts "> total: #{ARGV.size}\trenamed: #{rename_count}\tskipped: #{skip_count}"
