#!/usr/bin/env ruby
#
# name     : rmshit, remove shit in funtoo
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 May 27
# modified : 2013 Aug 24
#

files = %w[
  cache/ctrlp/hist/cache.txt
  cache/ctrlp/mru/cache.txt
  cmus/command-history
  cmus/search-history
  irb_history
  lesshst
  local/share/zathura/bookmarks
  mysql_history
  pry_history
  rnd
  sdcv_history
  sqlite_history
  xsel.log
]

files.each do |f|
  path = "#{Dir.home}/.#{f}"
  if File.exist?(path)
    File.delete(path)
    puts "*** #{path} has been removed ..."
  else
    puts ">>> #{path} not found ..."
  end
end
